# Generated by Django 3.2 on 2021-04-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(max_length=200, null=True, verbose_name='CSS класс'),
        ),
    ]
